// Karnataka administrative reference data — used across signup, settings,
// users & roles, and case-assignment workflows.

export const KARNATAKA_DISTRICTS = [
  "Bagalkote",
  "Ballari",
  "Belagavi",
  "Bengaluru Rural",
  "Bengaluru Urban",
  "Bidar",
  "Chamarajanagara",
  "Chikkaballapura",
  "Chikkamagaluru",
  "Chitradurga",
  "Dakshina Kannada",
  "Davanagere",
  "Dharwad",
  "Gadag",
  "Hassan",
  "Haveri",
  "Kalaburagi",
  "Kodagu",
  "Kolar",
  "Koppal",
  "Mandya",
  "Mysuru",
  "Raichur",
  "Ramanagara",
  "Shivamogga",
  "Tumakuru",
  "Udupi",
  "Uttara Kannada",
  "Vijayanagara",
  "Vijayapura",
  "Yadgir",
] as const;

export const KARNATAKA_DEPARTMENTS = [
  "Department of Personnel & Administrative Reforms (DPAR)",
  "Revenue Department",
  "Urban Development Department",
  "Rural Development & Panchayat Raj",
  "Home Department",
  "Health & Family Welfare",
  "Medical Education",
  "Primary & Secondary Education",
  "Higher Education",
  "Finance Department",
  "Law, Justice & Human Rights",
  "Transport Department",
  "Public Works Department",
  "Water Resources Department",
  "Agriculture Department",
  "Horticulture Department",
  "Forest, Ecology & Environment",
  "Energy Department",
  "Commerce & Industries",
  "Information Technology, BT & S&T",
  "Women & Child Development",
  "Social Welfare Department",
  "Backward Classes Welfare",
  "Minorities Welfare",
  "Labour Department",
  "Food & Civil Supplies",
  "Housing Department",
  "Co-operation Department",
  "Youth Empowerment & Sports",
  "Kannada & Culture",
] as const;

export const ROLE_SCOPE: Record<
  string,
  { scope: string; canVerify: boolean; canPublish: boolean; canManage: boolean }
> = {
  super_admin: { scope: "All districts & departments", canVerify: true, canPublish: true, canManage: true },
  legal_officer: { scope: "Assigned department", canVerify: true, canPublish: true, canManage: false },
  reviewing_officer: { scope: "Assigned cases / district", canVerify: true, canPublish: false, canManage: false },
  department_admin: { scope: "Own department only", canVerify: false, canPublish: false, canManage: true },
  viewer: { scope: "Read-only across permitted scope", canVerify: false, canPublish: false, canManage: false },
};
